#!/bin/sh
# Update lists/debian.auto-*.list files

FILTERED_FILE=`dirname $0`"/lists/debian.filtered.list"
GREP_FILTERS_FILE=`dirname $0`"/lists/debian.grep-filters.txt"
if [ -e "$FILTERED_FILE" ]
then
    sed -ne 's/^\([^#]\+\)/^\1$/p' < "$FILTERED_FILE" > "$GREP_FILTERS_FILE"
fi

for PRIO in important required standard
do
    FILE=`dirname $0`"/lists/debian.auto-$PRIO.list"
    cat << EOF > "$FILE"
# Every Debian package which priority is $PRIO
# DON'T EDIT THIS FILE MANUALLY!
# IT WAS AUTOMATICALLY GENERATED BY $(basename $0)
# Date: $(date)

EOF
    # Enumerate all packages and filter on priority
    grep -E "^Package: |^Priority: $PRIO" /var/lib/dpkg/available | \
        grep "^Priority: " -B1 | \
        sed -ne 's/^Package: //p' | \
        grep -vEf "$GREP_FILTERS_FILE" | \
        sort >> "$FILE"
done
rm -f "$GREP_FILTERS_FILE"

