#!/bin/sh
# Update lists/debian.auto-*.list files

for PRIO in important required standard
do
    FILE=`dirname $0`"/lists/debian.auto-$PRIO.list"
    cat << EOF > "$FILE"
# All Debian package whose priority is $PRIO
# DON'T EDIT THIS FILE MANUALLY!
# IT WAS AUTOMATICALLY GENERATED BY $(basename $0)
# Date: $(date)

EOF
    grep "^Priority: $PRIO" -B10 /var/lib/dpkg/available | \
        sed -ne 's/^Package: //p' | \
        sort >> "$FILE"
done

